// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingVoteBE.Data;

#nullable disable

namespace TrainingVoteBE.Migrations
{
    [DbContext(typeof(VoteDbContext))]
    [Migration("20250212075405_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingVoteBE.Vote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Description = "Choose your favorite programming language",
                            Title = "What is your favorite programming language?"
                        });
                });

            modelBuilder.Entity("TrainingVoteBE.VoteOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VoteId");

                    b.ToTable("VoteOptions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Count = 0,
                            Text = "C#",
                            VoteId = "1"
                        },
                        new
                        {
                            Id = "2",
                            Count = 0,
                            Text = "Java",
                            VoteId = "1"
                        },
                        new
                        {
                            Id = "3",
                            Count = 0,
                            Text = "Python",
                            VoteId = "1"
                        });
                });

            modelBuilder.Entity("TrainingVoteBE.VoteOption", b =>
                {
                    b.HasOne("TrainingVoteBE.Vote", "Vote")
                        .WithMany("Options")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("TrainingVoteBE.Vote", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
